version: "3.8"

services:
  discord-bot:
    build: .
    image: discord_bot
    container_name: discord-bot
    env_file:
      - .env
    volumes:
      - ./assets:/app/assets
      - ./config:/app/config
      - ./log:/app/log
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
